/*
 * App Store Connect API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3.6.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(untagged)]
pub enum AlternativeDistributionPackageVersionsResponseIncludedInner {
    AlternativeDistributionPackageVariant(Box<models::AlternativeDistributionPackageVariant>),
    AlternativeDistributionPackageDelta(Box<models::AlternativeDistributionPackageDelta>),
    AlternativeDistributionPackage(Box<models::AlternativeDistributionPackage>),
}

impl Default for AlternativeDistributionPackageVersionsResponseIncludedInner {
    fn default() -> Self {
        Self::AlternativeDistributionPackageVariant(Default::default())
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Type {
    #[serde(rename = "alternativeDistributionPackageVariants")]
    AlternativeDistributionPackageVariants,
    #[serde(rename = "alternativeDistributionPackageDeltas")]
    AlternativeDistributionPackageDeltas,
    #[serde(rename = "alternativeDistributionPackages")]
    AlternativeDistributionPackages,
}

impl Default for Type {
    fn default() -> Type {
        Self::AlternativeDistributionPackageVariants
    }
}

