/*
 * App Store Connect API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3.6.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AppCustomProductPageCreateRequestDataRelationships {
    #[serde(rename = "app")]
    pub app: Box<models::AnalyticsReportRequestCreateRequestDataRelationshipsApp>,
    #[serde(rename = "appCustomProductPageVersions", skip_serializing_if = "Option::is_none")]
    pub app_custom_product_page_versions: Option<Box<models::AppCustomProductPageCreateRequestDataRelationshipsAppCustomProductPageVersions>>,
    #[serde(rename = "appStoreVersionTemplate", skip_serializing_if = "Option::is_none")]
    pub app_store_version_template: Option<Box<models::AppClipDefaultExperienceCreateRequestDataRelationshipsReleaseWithAppStoreVersion>>,
    #[serde(rename = "customProductPageTemplate", skip_serializing_if = "Option::is_none")]
    pub custom_product_page_template: Option<Box<models::AppCustomProductPageVersionRelationshipsAppCustomProductPage>>,
}

impl AppCustomProductPageCreateRequestDataRelationships {
    pub fn new(app: models::AnalyticsReportRequestCreateRequestDataRelationshipsApp) -> AppCustomProductPageCreateRequestDataRelationships {
        AppCustomProductPageCreateRequestDataRelationships {
            app: Box::new(app),
            app_custom_product_page_versions: None,
            app_store_version_template: None,
            custom_product_page_template: None,
        }
    }
}

