/*
 * App Store Connect API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3.6.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AppAvailabilityRelationships {
    #[serde(rename = "app", skip_serializing_if = "Option::is_none")]
    pub app: Option<Box<models::AlternativeDistributionKeyCreateRequestDataRelationshipsApp>>,
    #[serde(rename = "availableTerritories", skip_serializing_if = "Option::is_none")]
    pub available_territories: Option<Box<models::AppAvailabilityRelationshipsAvailableTerritories>>,
}

impl AppAvailabilityRelationships {
    pub fn new() -> AppAvailabilityRelationships {
        AppAvailabilityRelationships {
            app: None,
            available_territories: None,
        }
    }
}

