/*
 * App Store Connect API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3.6.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AppClipAdvancedExperienceLocalizationInlineCreate {
    #[serde(rename = "type")]
    pub r#type: Type,
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<String>,
    #[serde(rename = "attributes", skip_serializing_if = "Option::is_none")]
    pub attributes: Option<Box<models::AppClipAdvancedExperienceLocalizationAttributes>>,
}

impl AppClipAdvancedExperienceLocalizationInlineCreate {
    pub fn new(r#type: Type) -> AppClipAdvancedExperienceLocalizationInlineCreate {
        AppClipAdvancedExperienceLocalizationInlineCreate {
            r#type,
            id: None,
            attributes: None,
        }
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Type {
    #[serde(rename = "appClipAdvancedExperienceLocalizations")]
    AppClipAdvancedExperienceLocalizations,
}

impl Default for Type {
    fn default() -> Type {
        Self::AppClipAdvancedExperienceLocalizations
    }
}

