/*
 * App Store Connect API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3.6.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AppStoreReviewAttachmentRelationships {
    #[serde(rename = "appStoreReviewDetail", skip_serializing_if = "Option::is_none")]
    pub app_store_review_detail: Option<Box<models::AppStoreReviewAttachmentRelationshipsAppStoreReviewDetail>>,
}

impl AppStoreReviewAttachmentRelationships {
    pub fn new() -> AppStoreReviewAttachmentRelationships {
        AppStoreReviewAttachmentRelationships {
            app_store_review_detail: None,
        }
    }
}

