/*
 * App Store Connect API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3.6.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AppPreviewSetAttributes {
    #[serde(rename = "previewType", skip_serializing_if = "Option::is_none")]
    pub preview_type: Option<models::PreviewType>,
}

impl AppPreviewSetAttributes {
    pub fn new() -> AppPreviewSetAttributes {
        AppPreviewSetAttributes {
            preview_type: None,
        }
    }
}

