/*
 * App Store Connect API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3.6.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AppEncryptionDeclarationDocumentCreateRequestDataRelationships {
    #[serde(rename = "appEncryptionDeclaration")]
    pub app_encryption_declaration: Box<models::AppEncryptionDeclarationDocumentCreateRequestDataRelationshipsAppEncryptionDeclaration>,
}

impl AppEncryptionDeclarationDocumentCreateRequestDataRelationships {
    pub fn new(app_encryption_declaration: models::AppEncryptionDeclarationDocumentCreateRequestDataRelationshipsAppEncryptionDeclaration) -> AppEncryptionDeclarationDocumentCreateRequestDataRelationships {
        AppEncryptionDeclarationDocumentCreateRequestDataRelationships {
            app_encryption_declaration: Box::new(app_encryption_declaration),
        }
    }
}

