/*
 * App Store Connect API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3.6.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AppsBetaTesterUsagesV1MetricResponseDataInnerDataPointsValues {
    #[serde(rename = "crashCount", skip_serializing_if = "Option::is_none")]
    pub crash_count: Option<i32>,
    #[serde(rename = "sessionCount", skip_serializing_if = "Option::is_none")]
    pub session_count: Option<i32>,
    #[serde(rename = "feedbackCount", skip_serializing_if = "Option::is_none")]
    pub feedback_count: Option<i32>,
}

impl AppsBetaTesterUsagesV1MetricResponseDataInnerDataPointsValues {
    pub fn new() -> AppsBetaTesterUsagesV1MetricResponseDataInnerDataPointsValues {
        AppsBetaTesterUsagesV1MetricResponseDataInnerDataPointsValues {
            crash_count: None,
            session_count: None,
            feedback_count: None,
        }
    }
}

