/*
 * App Store Connect API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3.6.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct BetaAppLocalizationCreateRequestDataAttributes {
    #[serde(rename = "feedbackEmail", skip_serializing_if = "Option::is_none")]
    pub feedback_email: Option<String>,
    #[serde(rename = "marketingUrl", skip_serializing_if = "Option::is_none")]
    pub marketing_url: Option<String>,
    #[serde(rename = "privacyPolicyUrl", skip_serializing_if = "Option::is_none")]
    pub privacy_policy_url: Option<String>,
    #[serde(rename = "tvOsPrivacyPolicy", skip_serializing_if = "Option::is_none")]
    pub tv_os_privacy_policy: Option<String>,
    #[serde(rename = "description", skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    #[serde(rename = "locale")]
    pub locale: String,
}

impl BetaAppLocalizationCreateRequestDataAttributes {
    pub fn new(locale: String) -> BetaAppLocalizationCreateRequestDataAttributes {
        BetaAppLocalizationCreateRequestDataAttributes {
            feedback_email: None,
            marketing_url: None,
            privacy_policy_url: None,
            tv_os_privacy_policy: None,
            description: None,
            locale,
        }
    }
}

