/*
 * App Store Connect API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3.6.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct BetaGroupCreateRequestDataRelationships {
    #[serde(rename = "app")]
    pub app: Box<models::AnalyticsReportRequestCreateRequestDataRelationshipsApp>,
    #[serde(rename = "builds", skip_serializing_if = "Option::is_none")]
    pub builds: Option<Box<models::BetaGroupCreateRequestDataRelationshipsBuilds>>,
    #[serde(rename = "betaTesters", skip_serializing_if = "Option::is_none")]
    pub beta_testers: Option<Box<models::BetaGroupCreateRequestDataRelationshipsBetaTesters>>,
}

impl BetaGroupCreateRequestDataRelationships {
    pub fn new(app: models::AnalyticsReportRequestCreateRequestDataRelationshipsApp) -> BetaGroupCreateRequestDataRelationships {
        BetaGroupCreateRequestDataRelationships {
            app: Box::new(app),
            builds: None,
            beta_testers: None,
        }
    }
}

