/*
 * App Store Connect API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3.6.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct BuildRelationships {
    #[serde(rename = "preReleaseVersion", skip_serializing_if = "Option::is_none")]
    pub pre_release_version: Option<Box<models::BuildRelationshipsPreReleaseVersion>>,
    #[serde(rename = "individualTesters", skip_serializing_if = "Option::is_none")]
    pub individual_testers: Option<Box<models::BetaGroupRelationshipsBetaTesters>>,
    #[serde(rename = "betaGroups", skip_serializing_if = "Option::is_none")]
    pub beta_groups: Option<Box<models::AppRelationshipsBetaGroups>>,
    #[serde(rename = "betaBuildLocalizations", skip_serializing_if = "Option::is_none")]
    pub beta_build_localizations: Option<Box<models::BuildRelationshipsBetaBuildLocalizations>>,
    #[serde(rename = "appEncryptionDeclaration", skip_serializing_if = "Option::is_none")]
    pub app_encryption_declaration: Option<Box<models::BuildRelationshipsAppEncryptionDeclaration>>,
    #[serde(rename = "betaAppReviewSubmission", skip_serializing_if = "Option::is_none")]
    pub beta_app_review_submission: Option<Box<models::BuildRelationshipsBetaAppReviewSubmission>>,
    #[serde(rename = "app", skip_serializing_if = "Option::is_none")]
    pub app: Option<Box<models::BetaAppLocalizationRelationshipsApp>>,
    #[serde(rename = "buildBetaDetail", skip_serializing_if = "Option::is_none")]
    pub build_beta_detail: Option<Box<models::BuildRelationshipsBuildBetaDetail>>,
    #[serde(rename = "appStoreVersion", skip_serializing_if = "Option::is_none")]
    pub app_store_version: Option<Box<models::AppClipDefaultExperienceRelationshipsReleaseWithAppStoreVersion>>,
    #[serde(rename = "icons", skip_serializing_if = "Option::is_none")]
    pub icons: Option<Box<models::BuildRelationshipsIcons>>,
    #[serde(rename = "buildBundles", skip_serializing_if = "Option::is_none")]
    pub build_bundles: Option<Box<models::BuildRelationshipsBuildBundles>>,
    #[serde(rename = "perfPowerMetrics", skip_serializing_if = "Option::is_none")]
    pub perf_power_metrics: Option<Box<models::AnalyticsReportInstanceRelationshipsSegments>>,
    #[serde(rename = "diagnosticSignatures", skip_serializing_if = "Option::is_none")]
    pub diagnostic_signatures: Option<Box<models::AnalyticsReportInstanceRelationshipsSegments>>,
}

impl BuildRelationships {
    pub fn new() -> BuildRelationships {
        BuildRelationships {
            pre_release_version: None,
            individual_testers: None,
            beta_groups: None,
            beta_build_localizations: None,
            app_encryption_declaration: None,
            beta_app_review_submission: None,
            app: None,
            build_beta_detail: None,
            app_store_version: None,
            icons: None,
            build_bundles: None,
            perf_power_metrics: None,
            diagnostic_signatures: None,
        }
    }
}

