/*
 * App Store Connect API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3.6.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct BundleIdCapabilityCreateRequestDataRelationships {
    #[serde(rename = "bundleId")]
    pub bundle_id: Box<models::BundleIdCapabilityCreateRequestDataRelationshipsBundleId>,
}

impl BundleIdCapabilityCreateRequestDataRelationships {
    pub fn new(bundle_id: models::BundleIdCapabilityCreateRequestDataRelationshipsBundleId) -> BundleIdCapabilityCreateRequestDataRelationships {
        BundleIdCapabilityCreateRequestDataRelationships {
            bundle_id: Box::new(bundle_id),
        }
    }
}

