/*
 * App Store Connect API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3.6.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CiArtifactResponse {
    #[serde(rename = "data")]
    pub data: Box<models::CiArtifact>,
    #[serde(rename = "links")]
    pub links: Box<models::DocumentLinks>,
}

impl CiArtifactResponse {
    pub fn new(data: models::CiArtifact, links: models::DocumentLinks) -> CiArtifactResponse {
        CiArtifactResponse {
            data: Box::new(data),
            links: Box::new(links),
        }
    }
}

