/*
 * App Store Connect API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3.6.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CiProductRelationships {
    #[serde(rename = "app", skip_serializing_if = "Option::is_none")]
    pub app: Option<Box<models::BetaAppLocalizationRelationshipsApp>>,
    #[serde(rename = "bundleId", skip_serializing_if = "Option::is_none")]
    pub bundle_id: Option<Box<models::CiProductRelationshipsBundleId>>,
    #[serde(rename = "workflows", skip_serializing_if = "Option::is_none")]
    pub workflows: Option<Box<models::AnalyticsReportInstanceRelationshipsSegments>>,
    #[serde(rename = "primaryRepositories", skip_serializing_if = "Option::is_none")]
    pub primary_repositories: Option<Box<models::CiProductRelationshipsPrimaryRepositories>>,
    #[serde(rename = "additionalRepositories", skip_serializing_if = "Option::is_none")]
    pub additional_repositories: Option<Box<models::AnalyticsReportInstanceRelationshipsSegments>>,
    #[serde(rename = "buildRuns", skip_serializing_if = "Option::is_none")]
    pub build_runs: Option<Box<models::AnalyticsReportInstanceRelationshipsSegments>>,
}

impl CiProductRelationships {
    pub fn new() -> CiProductRelationships {
        CiProductRelationships {
            app: None,
            bundle_id: None,
            workflows: None,
            primary_repositories: None,
            additional_repositories: None,
            build_runs: None,
        }
    }
}

