/*
 * App Store Connect API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3.6.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CiWorkflowRelationships {
    #[serde(rename = "product", skip_serializing_if = "Option::is_none")]
    pub product: Option<Box<models::CiBuildRunRelationshipsProduct>>,
    #[serde(rename = "repository", skip_serializing_if = "Option::is_none")]
    pub repository: Option<Box<models::CiWorkflowRelationshipsRepository>>,
    #[serde(rename = "xcodeVersion", skip_serializing_if = "Option::is_none")]
    pub xcode_version: Option<Box<models::CiWorkflowRelationshipsXcodeVersion>>,
    #[serde(rename = "macOsVersion", skip_serializing_if = "Option::is_none")]
    pub mac_os_version: Option<Box<models::CiWorkflowRelationshipsMacOsVersion>>,
    #[serde(rename = "buildRuns", skip_serializing_if = "Option::is_none")]
    pub build_runs: Option<Box<models::AnalyticsReportInstanceRelationshipsSegments>>,
}

impl CiWorkflowRelationships {
    pub fn new() -> CiWorkflowRelationships {
        CiWorkflowRelationships {
            product: None,
            repository: None,
            xcode_version: None,
            mac_os_version: None,
            build_runs: None,
        }
    }
}

