/*
 * App Store Connect API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3.6.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CustomerReviewAttributes {
    #[serde(rename = "rating", skip_serializing_if = "Option::is_none")]
    pub rating: Option<i32>,
    #[serde(rename = "title", skip_serializing_if = "Option::is_none")]
    pub title: Option<String>,
    #[serde(rename = "body", skip_serializing_if = "Option::is_none")]
    pub body: Option<String>,
    #[serde(rename = "reviewerNickname", skip_serializing_if = "Option::is_none")]
    pub reviewer_nickname: Option<String>,
    #[serde(rename = "createdDate", skip_serializing_if = "Option::is_none")]
    pub created_date: Option<String>,
    #[serde(rename = "territory", skip_serializing_if = "Option::is_none")]
    pub territory: Option<models::TerritoryCode>,
}

impl CustomerReviewAttributes {
    pub fn new() -> CustomerReviewAttributes {
        CustomerReviewAttributes {
            rating: None,
            title: None,
            body: None,
            reviewer_nickname: None,
            created_date: None,
            territory: None,
        }
    }
}

