/*
 * App Store Connect API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3.6.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct DiagnosticLogs {
    #[serde(rename = "productData", skip_serializing_if = "Option::is_none")]
    pub product_data: Option<Vec<models::DiagnosticLogsProductDataInner>>,
    #[serde(rename = "version", skip_serializing_if = "Option::is_none")]
    pub version: Option<String>,
}

impl DiagnosticLogs {
    pub fn new() -> DiagnosticLogs {
        DiagnosticLogs {
            product_data: None,
            version: None,
        }
    }
}

