/*
 * App Store Connect API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3.6.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct DiagnosticLogCallStackNode {
    #[serde(rename = "sampleCount", skip_serializing_if = "Option::is_none")]
    pub sample_count: Option<i32>,
    #[serde(rename = "isBlameFrame", skip_serializing_if = "Option::is_none")]
    pub is_blame_frame: Option<bool>,
    #[serde(rename = "symbolName", skip_serializing_if = "Option::is_none")]
    pub symbol_name: Option<String>,
    #[serde(rename = "insightsCategory", skip_serializing_if = "Option::is_none")]
    pub insights_category: Option<String>,
    #[serde(rename = "offsetIntoSymbol", skip_serializing_if = "Option::is_none")]
    pub offset_into_symbol: Option<String>,
    #[serde(rename = "binaryName", skip_serializing_if = "Option::is_none")]
    pub binary_name: Option<String>,
    #[serde(rename = "fileName", skip_serializing_if = "Option::is_none")]
    pub file_name: Option<String>,
    #[serde(rename = "binaryUUID", skip_serializing_if = "Option::is_none")]
    pub binary_uuid: Option<String>,
    #[serde(rename = "lineNumber", skip_serializing_if = "Option::is_none")]
    pub line_number: Option<String>,
    #[serde(rename = "address", skip_serializing_if = "Option::is_none")]
    pub address: Option<String>,
    #[serde(rename = "offsetIntoBinaryTextSegment", skip_serializing_if = "Option::is_none")]
    pub offset_into_binary_text_segment: Option<String>,
    #[serde(rename = "rawFrame", skip_serializing_if = "Option::is_none")]
    pub raw_frame: Option<String>,
    #[serde(rename = "subFrames", skip_serializing_if = "Option::is_none")]
    pub sub_frames: Option<Vec<models::DiagnosticLogCallStackNode>>,
}

impl DiagnosticLogCallStackNode {
    pub fn new() -> DiagnosticLogCallStackNode {
        DiagnosticLogCallStackNode {
            sample_count: None,
            is_blame_frame: None,
            symbol_name: None,
            insights_category: None,
            offset_into_symbol: None,
            binary_name: None,
            file_name: None,
            binary_uuid: None,
            line_number: None,
            address: None,
            offset_into_binary_text_segment: None,
            raw_frame: None,
            sub_frames: None,
        }
    }
}

