/*
 * App Store Connect API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3.6.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GameCenterMatchmakingAppRequestsV1MetricResponseDataInnerDimensions {
    #[serde(rename = "result", skip_serializing_if = "Option::is_none")]
    pub result: Option<Box<models::GameCenterMatchmakingAppRequestsV1MetricResponseDataInnerDimensionsResult>>,
}

impl GameCenterMatchmakingAppRequestsV1MetricResponseDataInnerDimensions {
    pub fn new() -> GameCenterMatchmakingAppRequestsV1MetricResponseDataInnerDimensions {
        GameCenterMatchmakingAppRequestsV1MetricResponseDataInnerDimensions {
            result: None,
        }
    }
}

