/*
 * App Store Connect API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3.6.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GameCenterMatchmakingSessionsV1MetricResponseDataInnerDataPointsValues {
    #[serde(rename = "count", skip_serializing_if = "Option::is_none")]
    pub count: Option<i32>,
    #[serde(rename = "averagePlayerCount", skip_serializing_if = "Option::is_none")]
    pub average_player_count: Option<f64>,
    #[serde(rename = "p50PlayerCount", skip_serializing_if = "Option::is_none")]
    pub p50_player_count: Option<f64>,
    #[serde(rename = "p95PlayerCount", skip_serializing_if = "Option::is_none")]
    pub p95_player_count: Option<f64>,
}

impl GameCenterMatchmakingSessionsV1MetricResponseDataInnerDataPointsValues {
    pub fn new() -> GameCenterMatchmakingSessionsV1MetricResponseDataInnerDataPointsValues {
        GameCenterMatchmakingSessionsV1MetricResponseDataInnerDataPointsValues {
            count: None,
            average_player_count: None,
            p50_player_count: None,
            p95_player_count: None,
        }
    }
}

