/*
 * App Store Connect API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3.6.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GameCenterMatchmakingQueueSizesV1MetricResponseDataInnerDataPointsValues {
    #[serde(rename = "count", skip_serializing_if = "Option::is_none")]
    pub count: Option<i32>,
    #[serde(rename = "averageNumberOfRequests", skip_serializing_if = "Option::is_none")]
    pub average_number_of_requests: Option<f64>,
    #[serde(rename = "p50NumberOfRequests", skip_serializing_if = "Option::is_none")]
    pub p50_number_of_requests: Option<f64>,
    #[serde(rename = "p95NumberOfRequests", skip_serializing_if = "Option::is_none")]
    pub p95_number_of_requests: Option<f64>,
}

impl GameCenterMatchmakingQueueSizesV1MetricResponseDataInnerDataPointsValues {
    pub fn new() -> GameCenterMatchmakingQueueSizesV1MetricResponseDataInnerDataPointsValues {
        GameCenterMatchmakingQueueSizesV1MetricResponseDataInnerDataPointsValues {
            count: None,
            average_number_of_requests: None,
            p50_number_of_requests: None,
            p95_number_of_requests: None,
        }
    }
}

