/*
 * App Store Connect API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3.6.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GameCenterLeaderboardSetMemberLocalizationRelationships {
    #[serde(rename = "gameCenterLeaderboardSet", skip_serializing_if = "Option::is_none")]
    pub game_center_leaderboard_set: Option<Box<models::GameCenterLeaderboardSetMemberLocalizationRelationshipsGameCenterLeaderboardSet>>,
    #[serde(rename = "gameCenterLeaderboard", skip_serializing_if = "Option::is_none")]
    pub game_center_leaderboard: Option<Box<models::GameCenterLeaderboardSetMemberLocalizationRelationshipsGameCenterLeaderboard>>,
}

impl GameCenterLeaderboardSetMemberLocalizationRelationships {
    pub fn new() -> GameCenterLeaderboardSetMemberLocalizationRelationships {
        GameCenterLeaderboardSetMemberLocalizationRelationships {
            game_center_leaderboard_set: None,
            game_center_leaderboard: None,
        }
    }
}

