/*
 * App Store Connect API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3.6.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GameCenterLeaderboardImageRelationships {
    #[serde(rename = "gameCenterLeaderboardLocalization", skip_serializing_if = "Option::is_none")]
    pub game_center_leaderboard_localization: Option<Box<models::GameCenterLeaderboardImageRelationshipsGameCenterLeaderboardLocalization>>,
}

impl GameCenterLeaderboardImageRelationships {
    pub fn new() -> GameCenterLeaderboardImageRelationships {
        GameCenterLeaderboardImageRelationships {
            game_center_leaderboard_localization: None,
        }
    }
}

