/*
 * App Store Connect API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3.6.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GameCenterAchievementUpdateRequestDataAttributes {
    #[serde(rename = "referenceName", skip_serializing_if = "Option::is_none")]
    pub reference_name: Option<String>,
    #[serde(rename = "points", skip_serializing_if = "Option::is_none")]
    pub points: Option<i32>,
    #[serde(rename = "showBeforeEarned", skip_serializing_if = "Option::is_none")]
    pub show_before_earned: Option<bool>,
    #[serde(rename = "repeatable", skip_serializing_if = "Option::is_none")]
    pub repeatable: Option<bool>,
    #[serde(rename = "archived", skip_serializing_if = "Option::is_none")]
    pub archived: Option<bool>,
}

impl GameCenterAchievementUpdateRequestDataAttributes {
    pub fn new() -> GameCenterAchievementUpdateRequestDataAttributes {
        GameCenterAchievementUpdateRequestDataAttributes {
            reference_name: None,
            points: None,
            show_before_earned: None,
            repeatable: None,
            archived: None,
        }
    }
}

