/*
 * App Store Connect API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3.6.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(untagged)]
pub enum GameCenterLeaderboardLocalizationsResponseIncludedInner {
    GameCenterLeaderboard(Box<models::GameCenterLeaderboard>),
    GameCenterLeaderboardImage(Box<models::GameCenterLeaderboardImage>),
}

impl Default for GameCenterLeaderboardLocalizationsResponseIncludedInner {
    fn default() -> Self {
        Self::GameCenterLeaderboard(Default::default())
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Type {
    #[serde(rename = "gameCenterLeaderboards")]
    GameCenterLeaderboards,
    #[serde(rename = "gameCenterLeaderboardImages")]
    GameCenterLeaderboardImages,
}

impl Default for Type {
    fn default() -> Type {
        Self::GameCenterLeaderboards
    }
}

