/*
 * App Store Connect API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3.6.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct InAppPurchasePriceScheduleCreateRequestDataRelationships {
    #[serde(rename = "inAppPurchase")]
    pub in_app_purchase: Box<models::InAppPurchaseAppStoreReviewScreenshotCreateRequestDataRelationshipsInAppPurchaseV2>,
    #[serde(rename = "baseTerritory")]
    pub base_territory: Box<models::AppPriceScheduleCreateRequestDataRelationshipsBaseTerritory>,
    #[serde(rename = "manualPrices")]
    pub manual_prices: Box<models::InAppPurchasePriceScheduleCreateRequestDataRelationshipsManualPrices>,
}

impl InAppPurchasePriceScheduleCreateRequestDataRelationships {
    pub fn new(in_app_purchase: models::InAppPurchaseAppStoreReviewScreenshotCreateRequestDataRelationshipsInAppPurchaseV2, base_territory: models::AppPriceScheduleCreateRequestDataRelationshipsBaseTerritory, manual_prices: models::InAppPurchasePriceScheduleCreateRequestDataRelationshipsManualPrices) -> InAppPurchasePriceScheduleCreateRequestDataRelationships {
        InAppPurchasePriceScheduleCreateRequestDataRelationships {
            in_app_purchase: Box::new(in_app_purchase),
            base_territory: Box::new(base_territory),
            manual_prices: Box::new(manual_prices),
        }
    }
}

