/*
 * App Store Connect API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3.6.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct InAppPurchaseLocalizationCreateRequestDataAttributes {
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "locale")]
    pub locale: String,
    #[serde(rename = "description", skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
}

impl InAppPurchaseLocalizationCreateRequestDataAttributes {
    pub fn new(name: String, locale: String) -> InAppPurchaseLocalizationCreateRequestDataAttributes {
        InAppPurchaseLocalizationCreateRequestDataAttributes {
            name,
            locale,
            description: None,
        }
    }
}

