/*
 * App Store Connect API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3.6.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PromotedPurchaseCreateRequestDataRelationships {
    #[serde(rename = "app")]
    pub app: Box<models::AnalyticsReportRequestCreateRequestDataRelationshipsApp>,
    #[serde(rename = "inAppPurchaseV2", skip_serializing_if = "Option::is_none")]
    pub in_app_purchase_v2: Option<Box<models::InAppPurchaseAppStoreReviewScreenshotRelationshipsInAppPurchaseV2>>,
    #[serde(rename = "subscription", skip_serializing_if = "Option::is_none")]
    pub subscription: Option<Box<models::PromotedPurchaseRelationshipsSubscription>>,
}

impl PromotedPurchaseCreateRequestDataRelationships {
    pub fn new(app: models::AnalyticsReportRequestCreateRequestDataRelationshipsApp) -> PromotedPurchaseCreateRequestDataRelationships {
        PromotedPurchaseCreateRequestDataRelationships {
            app: Box::new(app),
            in_app_purchase_v2: None,
            subscription: None,
        }
    }
}

