/*
 * App Store Connect API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3.6.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ReviewSubmissionRelationships {
    #[serde(rename = "app", skip_serializing_if = "Option::is_none")]
    pub app: Option<Box<models::AlternativeDistributionKeyCreateRequestDataRelationshipsApp>>,
    #[serde(rename = "items", skip_serializing_if = "Option::is_none")]
    pub items: Option<Box<models::ReviewSubmissionRelationshipsItems>>,
    #[serde(rename = "appStoreVersionForReview", skip_serializing_if = "Option::is_none")]
    pub app_store_version_for_review: Option<Box<models::AppClipDefaultExperienceCreateRequestDataRelationshipsReleaseWithAppStoreVersion>>,
    #[serde(rename = "submittedByActor", skip_serializing_if = "Option::is_none")]
    pub submitted_by_actor: Option<Box<models::ReviewSubmissionRelationshipsSubmittedByActor>>,
    #[serde(rename = "lastUpdatedByActor", skip_serializing_if = "Option::is_none")]
    pub last_updated_by_actor: Option<Box<models::ReviewSubmissionRelationshipsSubmittedByActor>>,
}

impl ReviewSubmissionRelationships {
    pub fn new() -> ReviewSubmissionRelationships {
        ReviewSubmissionRelationships {
            app: None,
            items: None,
            app_store_version_for_review: None,
            submitted_by_actor: None,
            last_updated_by_actor: None,
        }
    }
}

