/*
 * App Store Connect API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3.6.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct SubscriptionUpdateRequestDataAttributes {
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    #[serde(rename = "familySharable", skip_serializing_if = "Option::is_none")]
    pub family_sharable: Option<bool>,
    #[serde(rename = "subscriptionPeriod", skip_serializing_if = "Option::is_none")]
    pub subscription_period: Option<SubscriptionPeriod>,
    #[serde(rename = "reviewNote", skip_serializing_if = "Option::is_none")]
    pub review_note: Option<String>,
    #[serde(rename = "groupLevel", skip_serializing_if = "Option::is_none")]
    pub group_level: Option<i32>,
}

impl SubscriptionUpdateRequestDataAttributes {
    pub fn new() -> SubscriptionUpdateRequestDataAttributes {
        SubscriptionUpdateRequestDataAttributes {
            name: None,
            family_sharable: None,
            subscription_period: None,
            review_note: None,
            group_level: None,
        }
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum SubscriptionPeriod {
    #[serde(rename = "ONE_WEEK")]
    OneWeek,
    #[serde(rename = "ONE_MONTH")]
    OneMonth,
    #[serde(rename = "TWO_MONTHS")]
    TwoMonths,
    #[serde(rename = "THREE_MONTHS")]
    ThreeMonths,
    #[serde(rename = "SIX_MONTHS")]
    SixMonths,
    #[serde(rename = "ONE_YEAR")]
    OneYear,
}

impl Default for SubscriptionPeriod {
    fn default() -> SubscriptionPeriod {
        Self::OneWeek
    }
}

