/*
 * App Store Connect API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3.6.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct SubscriptionOfferCodeCustomCodeCreateRequestDataRelationships {
    #[serde(rename = "offerCode")]
    pub offer_code: Box<models::SubscriptionOfferCodeCustomCodeCreateRequestDataRelationshipsOfferCode>,
}

impl SubscriptionOfferCodeCustomCodeCreateRequestDataRelationships {
    pub fn new(offer_code: models::SubscriptionOfferCodeCustomCodeCreateRequestDataRelationshipsOfferCode) -> SubscriptionOfferCodeCustomCodeCreateRequestDataRelationships {
        SubscriptionOfferCodeCustomCodeCreateRequestDataRelationships {
            offer_code: Box::new(offer_code),
        }
    }
}

