/*
 * App Store Connect API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3.6.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct UserInvitationCreateRequestDataAttributes {
    #[serde(rename = "email")]
    pub email: String,
    #[serde(rename = "firstName")]
    pub first_name: String,
    #[serde(rename = "lastName")]
    pub last_name: String,
    #[serde(rename = "roles")]
    pub roles: Vec<models::UserRole>,
    #[serde(rename = "allAppsVisible", skip_serializing_if = "Option::is_none")]
    pub all_apps_visible: Option<bool>,
    #[serde(rename = "provisioningAllowed", skip_serializing_if = "Option::is_none")]
    pub provisioning_allowed: Option<bool>,
}

impl UserInvitationCreateRequestDataAttributes {
    pub fn new(email: String, first_name: String, last_name: String, roles: Vec<models::UserRole>) -> UserInvitationCreateRequestDataAttributes {
        UserInvitationCreateRequestDataAttributes {
            email,
            first_name,
            last_name,
            roles,
            all_apps_visible: None,
            provisioning_allowed: None,
        }
    }
}

