/*
 * App Store Connect API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3.6.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct WinBackOfferCreateRequestDataRelationships {
    #[serde(rename = "subscription")]
    pub subscription: Box<models::SubscriptionAppStoreReviewScreenshotCreateRequestDataRelationshipsSubscription>,
    #[serde(rename = "prices")]
    pub prices: Box<models::WinBackOfferCreateRequestDataRelationshipsPrices>,
}

impl WinBackOfferCreateRequestDataRelationships {
    pub fn new(subscription: models::SubscriptionAppStoreReviewScreenshotCreateRequestDataRelationshipsSubscription, prices: models::WinBackOfferCreateRequestDataRelationshipsPrices) -> WinBackOfferCreateRequestDataRelationships {
        WinBackOfferCreateRequestDataRelationships {
            subscription: Box::new(subscription),
            prices: Box::new(prices),
        }
    }
}

